name: Build and test
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run every hour. This helps detect flakiness,
    # and broken external dependencies.
    - cron: "0 * * * *"

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros: humble
            ubuntu: jammy
          - ros: rolling
            ubuntu: jammy

    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu }}-latest

    name: ROS 2 ${{ matrix.ros }}
    steps:
      - name: Build and run tests
        id: action-ros-ci
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: bag2_to_image
          target-ros2-distro: ${{ matrix.ros }}
      - uses: actions/upload-artifact@v3
        with:
          name: colcon-logs
          path: ros_ws/log